package com.szakdoga.backend.courses.models;

import lombok.Getter;

@Getter
public enum LocationEnum {
    //tests generated by ChatGPT, change these for further development
    //for example: store these in a table, make CRUD...
    BOLYAI_AMPHITHEATER("Bolyai Amphitheater"),
    AUD_MAX("Auditorium Maximum"),
    JOZSEF_ATTILA_STUDY_ROOM("József Attila Study Room"),
    TIK_ROOM_1("TIK Room 1"),
    TIK_ROOM_2("TIK Room 2"),
    ARADI_VERTANUK_ROOM("Aradi Vértanúk Room"),
    DOM_TER_ROOM_1("Dóm Tér Room 1"),
    DOM_TER_ROOM_2("Dóm Tér Room 2"),
    KALVARIA_SGT_ROOM_1("Kálvária sgt. Room 1"),
    KALVARIA_SGT_ROOM_2("Kálvária sgt. Room 2"),
    ONLINE("Online");

    private final String locationName;

    LocationEnum(String locationName) {
        this.locationName = locationName;
    }

    public static LocationEnum fromString(String locationName) {
        for (LocationEnum location : values()) {
            if (location.locationName.equalsIgnoreCase(locationName)) {
                return location;
            }
        }
        throw new IllegalArgumentException("No enum constant for location: " + locationName);
    }
}
